### ISSUE TITLE
Fails to build with boost-1.74

### ISSUE THREAD

**Issue by TheGreatMcPain** [foxdproject/foxdcoin#3]
I'm trying to compile on Gentoo which only has boost versions 1.74 and 1.75 available.

When attempting to compile I get a lot of...
```
validationinterface.cpp: In function ‘void RegisterValidationInterface(CValidationInterface*)’:
validationinterface.cpp:65:115: error: ‘_1’ was not declared in this scope
```

[Here's the output from `./make`](https://github.com/foxdproject/foxdcoin/files/6051884/build.log)
